// let nombre="sergio"

// let text="visit microsof";
// let result=

// let numero="12.5555566"

// const array =["jose","nico","alan"]

const theList = ['Laurence', 'Svekis', true, 35, null, undefined, ['one', 'two']]

theList.pop()
theList.pop()
theList.pop()
theList.pop()
theList.pop()

console.log(theList)

theList.shift()
console.log(theList)

theList.unshift("FIRST")
console.log(theList)
theList.push("MIDDLE")
console.log(theList)
theList.push("MIDDLE","hello World","LAST")
console.log(theList)


